In [1]:
import pickle
import os
import base64

file_path = r'D:\comment_data.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
x=img_dict['x']
y=img_dict['y']

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_sequences = pad_sequences(sequences, maxlen=300, padding='post', dtype='float32')

#print("Padded sequences:\n", padded_sequences)
#padded_sequences

D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:5

In [3]:
padded_y=np.array(y)
#padded_y.shape

In [4]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Define the number of folds for cross-validation
k = 3

# Initialize lists to store performance metrics across folds
mse_scores = []
r2_scores = []

# Create a Ridge regression model
ridge_model = Ridge(alpha=1.0)  # You can adjust alpha as needed

# Create a KFold object
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform k-fold cross-validation
for train_index, test_index in kf.split(padded_sequences):
    x_train, x_test = padded_sequences[train_index], padded_sequences[test_index]
    y_train, y_test = padded_y[train_index], padded_y[test_index]
    
    # Fit the model on the training data
    ridge_model.fit(x_train, y_train)
    
    # Predict on the test data
    y_pred = ridge_model.predict(x_test)
    print("Predictions:\n", y_pred)
    # Calculate performance metrics
    mse = mean_squared_error(y_test, y_pred)
    
    
    # Append scores to lists
    mse_scores.append(mse)
    

# Calculate mean and standard deviation of scores across folds
mean_mse = np.mean(mse_scores)
std_mse = np.std(mse_scores)

print(f"Mean MSE across {k}-fold CV: {mean_mse:.6f} ± {std_mse:.6f}")

Predictions:
 [[0.18299924 0.206663   0.21632946 0.17800045 0.2166726 ]
 [0.18299863 0.20666184 0.21632673 0.17800398 0.21667384]
 [0.18299945 0.20665726 0.21632595 0.17801245 0.2166716 ]
 [0.18301015 0.2066618  0.21634024 0.17799331 0.21665771]
 [0.18299979 0.20666407 0.21633197 0.17799719 0.21667145]
 [0.18301073 0.20667061 0.21631207 0.17799778 0.21667102]
 [0.18301961 0.20665093 0.21633574 0.17797624 0.21669039]
 [0.18296953 0.20666246 0.21635003 0.17799546 0.21668553]
 [0.18301801 0.20666035 0.21631186 0.17801394 0.21666181]
 [0.18297763 0.20671076 0.2163956  0.17791347 0.21666218]
 [0.18300009 0.20664889 0.2163489  0.1779955  0.21667378]
 [0.18299933 0.20666316 0.21632983 0.17799996 0.21667244]
 [0.18298419 0.20664373 0.21634515 0.17803177 0.216665  ]
 [0.18299894 0.20666243 0.21632813 0.17800218 0.2166732 ]
 [0.18299924 0.206663   0.21632946 0.17800045 0.2166726 ]
 [0.18299933 0.20666316 0.21632983 0.17799996 0.21667244]
 [0.18300296 0.20666154 0.21632859 0.17800492 0.21666811]


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and wil

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [6]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Create a Ridge regression model with regularization strength (alpha) set to 1.0
ridge_model1 = Ridge(alpha=1.0)

# Train the model
ridge_model1.fit(x_train, y_train)

# Predictions
y_pred = ridge_model1.predict(x_test)

# Print the predictions
print("Predictions:\n", y_pred)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18209697 0.20518386 0.21617092 0.17876592 0.21777998]
 [0.18210791 0.20517357 0.21617024 0.1787449  0.2178103 ]
 [0.1820991  0.20518509 0.2161802  0.17876059 0.21777046]
 [0.18208772 0.20518856 0.21617699 0.17875947 0.21778148]
 [0.18209697 0.20518386 0.21617092 0.17876592 0.21777998]
 [0.18206312 0.20518307 0.2161864  0.17876013 0.21780176]
 [0.18209662 0.20518366 0.21616934 0.17876683 0.2177816 ]
 [0.18212938 0.20514503 0.21615109 0.17880112 0.21778712]
 [0.18209717 0.2051797  0.21616668 0.17877455 0.21778288]]
Mean Squared Error: 0.0009817268986836176


In [8]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
# Create a Lasso regression model with regularization strength (alpha) set to 1.0
lasso_model = Lasso(alpha=1.0)

# Train the model
lasso_model.fit(x_train, y_train)

# Predictions
y_pred = lasso_model.predict(x_test)
from sklearn.metrics import mean_squared_error, r2_score
# Print the predictions
print("Predictions:\n", y_pred)

print(y_test)
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]
 [0.18209876 0.20518519 0.21617284 0.17876543 0.21777782]]
[['0.23' '0.23' '0.15' '0.18' '0.21']
 ['0.1' '0.25' '0.29' '0.15' '0.22']
 ['0.19' '0.21' '0.2' '0.13' '0.27']
 ['0.16' '0.19' '0.22' '0.19' '0.24']
 ['0.22' '0.2' '0.2' '0.2' '0.18']
 ['0.14' '0.19' '0.23' '0.19' '0.24']
 ['0.2' '0.18' '0.21' '0.2' '0.21']
 ['0.14' '0.22' '0.24' '0.21' '0.19']
 ['0.18' '0.21' '0.23' '0.14' '0.25']]
Mean Squared Error: 0.000981700842168285


In [11]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
# Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)
y_pred_rf = rf_model.predict(x_test)
rf_mse = mean_squared_error(y_test, y_pred_rf)
print(f"Random Forest Regressor MSE: {rf_mse}")

Random Forest Regressor MSE: 0.0013627976071062158


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [5]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
model = LinearRegression()
model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[0.5447058  0.55042565 0.553443   0.54550403 0.55485296]
 [0.9773406  0.5026854  0.58842963 0.06611504 0.42434937]
 [0.54574823 0.5502834  0.5534633  0.5449657  0.554276  ]
 [0.9363325  0.5379571  0.62696254 0.12871194 0.40763816]
 [0.5447058  0.55042565 0.553443   0.54550403 0.55485296]
 [0.52543646 0.55569285 0.5441322  0.56067926 0.55956686]
 [0.5445282  0.55044985 0.5534396  0.5455957  0.5549512 ]
 [0.9747039  0.5064281  0.7176411  0.07618608 0.25503585]
 [0.54563653 0.5499081  0.55413336 0.5476246  0.5525867 ]]
Mean Squared Error: 0.1470415980429129


In [11]:
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
multioutput_model = MultiOutputRegressor(LinearRegression())
multioutput_model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = multioutput_model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[0.5447058  0.55042565 0.5534431  0.54550403 0.55485296]
 [0.9773406  0.5026854  0.5884294  0.06611518 0.42434955]
 [0.54574823 0.5502834  0.5534633  0.5449657  0.55427605]
 [0.9363325  0.537957   0.62696254 0.12871213 0.4076383 ]
 [0.5447058  0.55042565 0.5534431  0.54550403 0.55485296]
 [0.5254364  0.55569285 0.54413223 0.56067926 0.55956686]
 [0.5445282  0.55044985 0.5534396  0.5455957  0.55495125]
 [0.9747039  0.50642794 0.7176409  0.07618637 0.25503603]
 [0.54563653 0.5499081  0.5541334  0.5476247  0.55258673]]
Mean Squared Error: 0.14704159434749303


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [6]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
model1 = LinearRegression()
model1.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = model1.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[3.9233685e-01 6.5135491e-01 6.1508787e-01 5.1561993e-01 5.5832702e-01]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00]
 [3.9233685e-01 6.5135491e-01 6.1508787e-01 5.1561993e-01 5.5253971e-01]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [3.9233685e-01 6.5135491e-01 6.1508787e-01 5.1561993e-01 5.5832702e-01]
 [2.8625186e-20 1.0000000e+00 1.0000000e+00 9.9972194e-01 6.5130358e-08]
 [3.9233685e-01 6.5135491e-01 6.1508787e-01 5.1561993e-01 5.5832702e-01]
 [0.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00]
 [2.8140563e-01 7.3105860e-01 6.6541058e-01 5.1561993e-01 5.1757091e-01]]
Mean Squared Error: 0.2539203768494678


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [13]:
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
multioutput_model = MultiOutputRegressor(LinearRegression())
multioutput_model.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = multioutput_model.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[4.6879062e-01 5.9266663e-01 5.6985265e-01 5.0000000e-01 5.5832702e-01]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00]
 [4.6879062e-01 5.9266663e-01 5.6985265e-01 5.0000000e-01 5.5253971e-01]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00]
 [4.6879062e-01 5.9266663e-01 5.6985265e-01 5.0000000e-01 5.5832702e-01]
 [3.4528564e-20 1.0000000e+00 1.0000000e+00 9.9968493e-01 6.4120606e-08]
 [4.6879062e-01 5.9266663e-01 5.6985265e-01 5.0000000e-01 5.5832702e-01]
 [0.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00 1.0000000e+00]
 [3.6296919e-01 6.6541058e-01 6.2245935e-01 5.0000000e-01 5.1757091e-01]]
Mean Squared Error: 0.24645760645013343


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


# new prediction

In [7]:
import pickle
import os
import base64

file_path = r'D:\new_comment.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
#print(img_dict.keys())
x=img_dict['x']
y=img_dict['y']

In [8]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_x = pad_sequences(sequences, maxlen=300, padding='post', dtype='float32')

In [9]:
padded_y=np.array(y[10])
padded_y

array(['0.18', '0.21', '0.23', '0.14', '0.25'], dtype='<U4')

In [10]:
reshaped_data = padded_x[10].reshape(1, -1)
y_pred = ridge_model.predict(reshaped_data)

# Print the predictions
print("Predictions:\n", y_pred)

Predictions:
 [[0.17816794 0.20499304 0.21666206 0.18033956 0.21933809]]


In [12]:
from sklearn.metrics import mean_squared_error
reshaped_y = padded_y.reshape(1,-1)
mse = mean_squared_error(reshaped_y, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0005547518998572007


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [1]:
post_text_weight = 0.68
comment_weight = 0.32
post_img_weight = 0.43
profile_img_weight = 0.63
import numpy as np

In [2]:
final_comment_prediction = np.array([[0.17816794,0.20499304,0.21666206,0.18033956,0.21933809]])

In [3]:
print(type(final_comment_prediction))

<class 'numpy.ndarray'>


In [4]:
final_post_prediction = np.array([[0.18013708,0.20583625,0.21803221,0.17628355,0.2190747 ]])

In [5]:
print(type(final_post_prediction))

<class 'numpy.ndarray'>


In [6]:
final_post_img_prediction = np.array([0.17933537065982819, 0.19528426229953766, 0.2029479742050171, 0.1652487963438034, 0.20580318570137024])

In [7]:
print(type(final_post_img_prediction))

<class 'numpy.ndarray'>


In [8]:
final_profile_img_prediction = np.array([0.07974329590797424, 0.10734947770833969, 0.0936485156416893, 0.09621872007846832, 0.1311817318201065])

In [9]:
print(type(final_profile_img_prediction))

<class 'numpy.ndarray'>


In [11]:
final_text_prediction = post_text_weight * final_post_prediction + comment_weight * final_comment_prediction
print(final_text_prediction)

[[0.17950696 0.20556642 0.21759376 0.17758147 0.21915898]]


In [14]:
y_ac=np.array([[0.18,0.21,0.23,0.14,0.25]])
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(final_text_prediction, y_ac)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0005074699575449522


# Averaging predictions

In [18]:
avg_text_pred = 0.5 * np.array([[0.17950696,0.20556642,0.21759376,0.17758147,0.21915898]]) + 0.5 * np.array([[0.18233853,0.20635441,0.21267351,0.1819865,0.21698282]])

In [19]:
print(avg_text_pred)

[[0.18092274 0.20596042 0.21513363 0.17978398 0.2180709 ]]


In [20]:
y_ac=np.array([[0.18,0.21,0.23,0.14,0.25]])
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(avg_text_pred, y_ac)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0005680822805821395


In [12]:
final_prediction = post_text_weight * final_post_prediction + comment_weight * final_comment_prediction + post_img_weight * final_post_img_prediction + profile_img_weight * final_profile_img_prediction

In [13]:
print(final_prediction)

[[0.30685944 0.35716883 0.36385996 0.30925625 0.39029885]]
