In [1]:
import pickle
import os
import base64

file_path = r'D:\LinkedInComment.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
x=img_dict['x']
y=img_dict['y']

In [36]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_sequences = pad_sequences(sequences, maxlen=500, padding='post', dtype='float32')

#print("Padded sequences:\n", padded_sequences)
#padded_sequences

In [37]:
padded_y=np.array(y)
#padded_y.shape

In [38]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Define the number of folds for cross-validation
k = 2

# Initialize lists to store performance metrics across folds
mse_scores = []
r2_scores = []

# Create a Ridge regression model
ridge_model = Ridge(alpha=1.0)  # You can adjust alpha as needed

# Create a KFold object
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform k-fold cross-validation
for train_index, test_index in kf.split(padded_sequences):
    x_train, x_test = padded_sequences[train_index], padded_sequences[test_index]
    y_train, y_test = padded_y[train_index], padded_y[test_index]
    
    # Fit the model on the training data
    ridge_model.fit(x_train, y_train)
    
    # Predict on the test data
    y_pred = ridge_model.predict(x_test)
    print("Predictions:\n", y_pred)
    # Calculate performance metrics
    mse = mean_squared_error(y_test, y_pred)
    
    
    # Append scores to lists
    mse_scores.append(mse)
    

# Calculate mean and standard deviation of scores across folds
mean_mse = np.mean(mse_scores)
std_mse = np.std(mse_scores)

print(f"Mean MSE across {k}-fold CV: {mean_mse:.6f} ± {std_mse:.6f}")

Predictions:
 [[0.18553343 0.20482309 0.2138014  0.17999463 0.21722665]
 [0.18553257 0.20482165 0.21380284 0.17999707 0.21722531]
 [0.18553498 0.20481735 0.21380079 0.1800029  0.21722238]
 [0.18553345 0.20481959 0.21379732 0.18000478 0.21722296]
 [0.18553993 0.20482032 0.21379912 0.17999545 0.21722326]
 [0.18553749 0.20481953 0.21379516 0.1800019  0.21722147]
 [0.18553182 0.20482238 0.21380185 0.17999849 0.21722598]
 [0.18555304 0.2048263  0.21379942 0.17996466 0.2172347 ]
 [0.18553215 0.20481963 0.2138135  0.18000624 0.21721156]
 [0.18554235 0.20482671 0.21379995 0.17997621 0.2172334 ]
 [0.18551867 0.20483221 0.21380512 0.17999206 0.21723434]
 [0.18550155 0.20484728 0.21378574 0.17998084 0.21726759]
 [0.18555512 0.20481598 0.21380843 0.17998858 0.21721022]
 [0.18553993 0.20482032 0.21379912 0.17999545 0.21722326]
 [0.18553993 0.20482032 0.21379912 0.17999545 0.21722326]
 [0.18552993 0.20482923 0.2137983  0.17998378 0.21723823]
 [0.18553951 0.2048211  0.21379903 0.17999399 0.21722446]


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [40]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Create a Ridge regression model with regularization strength (alpha) set to 1.0
ridge_model1 = Ridge(alpha=1.0)

# Train the model
ridge_model1.fit(x_train, y_train)

# Predictions
y_pred = ridge_model1.predict(x_test)

# Print the predictions
print("Predictions:\n", y_pred)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18491074 0.20566157 0.213592   0.1807505  0.2164067 ]
 [0.18491152 0.20565732 0.21358728 0.18076576 0.21639779]
 [0.18491054 0.20566392 0.21358538 0.18075053 0.21641278]
 [0.18491422 0.20565447 0.21360348 0.18076435 0.21638884]
 [0.18491921 0.20565791 0.21358794 0.18075296 0.21640146]
 [0.18490398 0.20566098 0.21359326 0.18076654 0.21639583]]
Mean Squared Error: 0.0016655499480038596


In [41]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
# Create a Lasso regression model with regularization strength (alpha) set to 1.0
lasso_model = Lasso(alpha=1.0)

# Train the model
lasso_model.fit(x_train, y_train)

# Predictions
y_pred = lasso_model.predict(x_test)
from sklearn.metrics import mean_squared_error, r2_score
# Print the predictions
print("Predictions:\n", y_pred)

print(y_test)
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]]
[[0.18 0.25 0.22 0.12 0.23]
 [0.25 0.17 0.18 0.19 0.21]
 [0.17 0.24 0.22 0.2  0.17]
 [0.08 0.17 0.2  0.28 0.26]
 [0.14 0.19 0.23 0.19 0.24]
 [0.23 0.21 0.21 0.12 0.23]]
Mean Squared Error: 0.0016654065386174275


In [42]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
# Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)
y_pred_rf = rf_model.predict(x_test)
rf_mse = mean_squared_error(y_test, y_pred_rf)
print(f"Random Forest Regressor MSE: {rf_mse}")

Random Forest Regressor MSE: 0.0016168111363951566


In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [44]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
model = LinearRegression()
model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[0.5650764  0.54929537 0.5257506  0.5620769  0.54634076]
 [0.62807655 0.5764179  0.5645958  0.51479876 0.4498767 ]
 [0.5124765  0.5761577  0.54039687 0.51155233 0.6101191 ]
 [0.3788733  0.67128175 0.4945937  0.4410432  0.7561975 ]
 [0.5446618  0.5493009  0.5542408  0.5467894  0.5545008 ]
 [0.5185807  0.51731914 0.5566422  0.57768923 0.5763135 ]]
Mean Squared Error: 0.12735529517164296


In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [46]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
model1 = LinearRegression()
model1.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = model1.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[9.2709976e-01 1.8905446e-02 9.9471867e-01 1.1247575e-03 9.8649383e-01]
 [1.1818139e-01 9.7935402e-01 4.2483211e-02 9.9304235e-01 4.5015529e-02]
 [9.9802953e-01 6.9748700e-07 9.9999666e-01 5.8505316e-07 9.9998903e-01]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00]
 [5.5374664e-01 5.4092389e-01 5.5977142e-01 5.4092389e-01 5.5060738e-01]
 [3.0574577e-03 9.9917042e-01 1.4367507e-06 1.0000000e+00 6.9221838e-05]]
Mean Squared Error: 0.2910593590439029


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


# new prediction

In [47]:
import pickle
import os
import base64

file_path = r'D:\new_comment.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
#print(img_dict.keys())
x=img_dict['x']
y=img_dict['y']

In [49]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_x = pad_sequences(sequences, maxlen=500, padding='post', dtype='float32')

In [50]:
padded_y=np.array(y[10])
padded_y

array(['0.18', '0.21', '0.23', '0.14', '0.25'], dtype='<U4')

In [51]:
reshaped_data = padded_x[10].reshape(1, -1)
y_pred = ridge_model.predict(reshaped_data)

# Print the predictions
print("Predictions:\n", y_pred)

Predictions:
 [[0.18233494 0.2063399  0.21266447 0.18200006 0.21699446]]


In [52]:
from sklearn.metrics import mean_squared_error
reshaped_y = padded_y.reshape(1,-1)
mse = mean_squared_error(reshaped_y, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0006345478008251115


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [62]:
post_text_weight = 0.5
comment_weight = 0.5
import numpy as np

In [53]:
final_comment_prediction = np.array([[0.18233494,0.2063399,0.21266447,0.18200006,0.21699446]])

In [54]:
print(type(final_comment_prediction))

<class 'numpy.ndarray'>


In [55]:
final_post_prediction = np.array([[0.18234211,0.20636892,0.21268255,0.18197294,0.21697119]])

In [56]:
print(type(final_post_prediction))

<class 'numpy.ndarray'>


In [57]:
#final_post_img_prediction = np.array([0.17933537065982819, 0.19528426229953766, 0.2029479742050171, 0.1652487963438034, 0.20580318570137024])

In [58]:
#print(type(final_post_img_prediction))

In [59]:
#final_profile_img_prediction = np.array([0.07974329590797424, 0.10734947770833969, 0.0936485156416893, 0.09621872007846832, 0.1311817318201065])

In [60]:
#print(type(final_profile_img_prediction))

In [63]:
final_text_prediction = post_text_weight * final_post_prediction + comment_weight * final_comment_prediction

In [64]:
print(final_text_prediction)

[[0.18233853 0.20635441 0.21267351 0.1819865  0.21698282]]


In [67]:
y_ac=np.array([[0.18,0.21,0.23,0.14,0.25]])

In [68]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(final_text_prediction, y_ac)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0006343932617148898
