In [1]:
import pickle
import os
import base64

file_path = r'D:\data_post.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
x=img_dict['x']
y=img_dict['y']

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_sequences = pad_sequences(sequences, maxlen=300, padding='post', dtype='float32')

#print("Padded sequences:\n", padded_sequences)
#padded_sequences

D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anacondafolder\envs\testenv\lib\site-packages\tensorflow\python\framework\dtypes.py:5

In [36]:
#padded_sequences.shape

In [4]:
padded_y=np.array(y)
#padded_y.shape

In [17]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Define the number of folds for cross-validation
k = 3

# Initialize lists to store performance metrics across folds
mse_scores = []
r2_scores = []

# Create a Ridge regression model
ridge_model = Ridge(alpha=1.0)  # You can adjust alpha as needed

# Create a KFold object
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform k-fold cross-validation
for train_index, test_index in kf.split(padded_sequences):
    x_train, x_test = padded_sequences[train_index], padded_sequences[test_index]
    y_train, y_test = padded_y[train_index], padded_y[test_index]
    
    # Fit the model on the training data
    ridge_model.fit(x_train, y_train)
    
    # Predict on the test data
    y_pred = ridge_model.predict(x_test)
    print("Predictions:\n", y_pred)
    # Calculate performance metrics
    mse = mean_squared_error(y_test, y_pred)
    
    
    # Append scores to lists
    mse_scores.append(mse)
    

# Calculate mean and standard deviation of scores across folds
mean_mse = np.mean(mse_scores)
std_mse = np.std(mse_scores)

print(f"Mean MSE across {k}-fold CV: {mean_mse:.6f} ± {std_mse:.6f}")

Predictions:
 [[0.18046862 0.20702183 0.21665756 0.17968358 0.21716894]
 [0.18048353 0.20705554 0.21661182 0.17966247 0.2171543 ]
 [0.18044749 0.20699997 0.21664576 0.17977376 0.21712022]
 [0.18050095 0.2070298  0.21665747 0.17958908 0.2172106 ]
 [0.18048409 0.20700692 0.21664983 0.17969361 0.21716273]
 [0.18046471 0.207012   0.21668056 0.17969313 0.21715297]
 [0.1804883  0.20701382 0.21665123 0.17966282 0.21717726]
 [0.18046862 0.20702183 0.21665756 0.17968358 0.21716894]
 [0.18047819 0.20695251 0.21663304 0.17977229 0.21715409]
 [0.18049923 0.20697393 0.21661672 0.17974047 0.21715873]
 [0.18050934 0.20698917 0.21662764 0.17972195 0.21714756]
 [0.18048528 0.20704375 0.2166445  0.17967854 0.21715096]
 [0.18048586 0.20701824 0.21662797 0.17969999 0.21716169]
 [0.18047126 0.20700294 0.21665242 0.1796997  0.2171574 ]
 [0.18046862 0.20702183 0.21665756 0.17968358 0.21716894]
 [0.18054141 0.206999   0.21658708 0.17966874 0.21719334]
 [0.1804812  0.207035   0.21664357 0.17965965 0.21717735]


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and wil

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [48]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Create a Ridge regression model with regularization strength (alpha) set to 1.0
ridge_model1 = Ridge(alpha=1.0)

# Train the model
ridge_model1.fit(x_train, y_train)

# Predictions
y_pred = ridge_model1.predict(x_test)

# Print the predictions
print("Predictions:\n", y_pred)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18146513 0.20508587 0.21728371 0.17839393 0.2177751 ]
 [0.1814786  0.20507976 0.21727331 0.17838481 0.21778117]
 [0.1815268  0.2050365  0.21724401 0.17843072 0.21776949]
 [0.18147396 0.20509529 0.21728846 0.17836978 0.21777335]
 [0.18146513 0.20508587 0.21728371 0.17839393 0.2177751 ]
 [0.18146513 0.20508587 0.21728371 0.17839393 0.2177751 ]
 [0.18143637 0.20505457 0.21727002 0.17846271 0.21775822]
 [0.18146513 0.20508587 0.21728371 0.17839393 0.2177751 ]
 [0.18143786 0.2050523  0.217257   0.17848964 0.21775946]]
Mean Squared Error: 0.000955469626995157


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [6]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
model = LinearRegression()
model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[5.4131484e-01 5.5298883e-01 5.5299795e-01 5.4464549e-01 5.5719888e-01]
 [6.6749772e-06 5.8979374e-08 4.5820805e-05 1.0000000e+00 3.1114752e-16]
 [1.0000000e+00 1.0000000e+00 1.0000000e+00 0.0000000e+00 1.0000000e+00]
 [5.2510572e-06 7.8746886e-08 8.0391932e-05 1.0000000e+00 7.8227257e-16]
 [5.4131484e-01 5.5298883e-01 5.5299795e-01 5.4464549e-01 5.5719888e-01]
 [5.4131484e-01 5.5298883e-01 5.5299795e-01 5.4464549e-01 5.5719888e-01]
 [9.0465753e-35 0.0000000e+00 9.7717188e-28 1.0000000e+00 0.0000000e+00]
 [5.4131484e-01 5.5298883e-01 5.5299795e-01 5.4464549e-01 5.5719888e-01]
 [0.0000000e+00 0.0000000e+00 4.2761083e-33 1.0000000e+00 0.0000000e+00]]
Mean Squared Error: 0.18774054526812892


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()


In [42]:
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
multioutput_model = MultiOutputRegressor(LinearRegression())
multioutput_model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = multioutput_model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[5.4131770e-01 5.5298644e-01 5.5300128e-01 5.4463226e-01 5.5720645e-01]
 [6.6735765e-06 5.8948096e-08 4.5798177e-05 1.0000000e+00 3.1063520e-16]
 [1.0000000e+00 1.0000000e+00 1.0000000e+00 0.0000000e+00 1.0000000e+00]
 [5.2503210e-06 7.8700637e-08 8.0357437e-05 1.0000000e+00 7.8137185e-16]
 [5.4131770e-01 5.5298644e-01 5.5300128e-01 5.4463226e-01 5.5720645e-01]
 [5.4131770e-01 5.5298644e-01 5.5300128e-01 5.4463226e-01 5.5720645e-01]
 [9.0369170e-35 0.0000000e+00 9.7414981e-28 1.0000000e+00 0.0000000e+00]
 [5.4131770e-01 5.5298644e-01 5.5300128e-01 5.4463226e-01 5.5720645e-01]
 [0.0000000e+00 0.0000000e+00 4.2608676e-33 1.0000000e+00 0.0000000e+00]]
Mean Squared Error: 0.18774042311997732


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:17: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [9]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
model1 = LinearRegression()
model1.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = model1.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[5.3072298e-01 5.4867351e-01 5.5380696e-01 5.5784535e-01 5.5726564e-01]
 [2.6001026e-23 5.8995397e-10 9.9073315e-01 1.0000000e+00 6.2954420e-01]
 [6.5809623e-17 2.0840361e-07 9.7089553e-01 1.0000000e+00 5.5673099e-01]
 [1.0000000e+00 1.0000000e+00 1.5690856e-07 0.0000000e+00 4.8465163e-01]
 [5.3072298e-01 5.4867351e-01 5.5380696e-01 5.5784535e-01 5.5726564e-01]
 [5.3072298e-01 5.4867351e-01 5.5380696e-01 5.5784535e-01 5.5726564e-01]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 7.0350254e-01]
 [5.3072298e-01 5.4867351e-01 5.5380696e-01 5.5784535e-01 5.5726564e-01]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 8.2643068e-01]]
Mean Squared Error: 0.22834858335981897


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [44]:
import numpy as np
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
multioutput_model = MultiOutputRegressor(LinearRegression())
multioutput_model.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = multioutput_model.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[5.3704137e-01 5.5133218e-01 5.5293202e-01 5.4189372e-01 5.5725527e-01]
 [2.5349155e-23 5.8650734e-10 9.9073642e-01 1.0000000e+00 6.2964207e-01]
 [6.6325777e-17 2.0759111e-07 9.7097474e-01 1.0000000e+00 5.5671781e-01]
 [1.0000000e+00 1.0000000e+00 1.5646863e-07 0.0000000e+00 4.8441058e-01]
 [5.3704137e-01 5.5133218e-01 5.5293202e-01 5.4189372e-01 5.5725527e-01]
 [5.3704137e-01 5.5133218e-01 5.5293202e-01 5.4189372e-01 5.5725527e-01]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 7.0316821e-01]
 [5.3704137e-01 5.5133218e-01 5.5293202e-01 5.4189372e-01 5.5725527e-01]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 8.2658827e-01]]
Mean Squared Error: 0.22782644704603663


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


# new prediction

In [24]:
import pickle
import os
import base64

file_path = r'D:\new_post.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
#print(img_dict.keys())
x=img_dict['x']
y=img_dict['y']

In [33]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_x = pad_sequences(sequences, maxlen=300, padding='post', dtype='float32')

In [35]:
padded_y=np.array(y[10])
padded_y

array(['0.18', '0.21', '0.23', '0.14', '0.25'], dtype='<U4')

In [32]:
reshaped_data = padded_x[10].reshape(1, -1)
y_pred = ridge_model.predict(reshaped_data)

# Print the predictions
print("Predictions:\n", y_pred)

Predictions:
 [[0.18013708 0.20583625 0.21803221 0.17628355 0.2190747 ]]


In [36]:
from sklearn.metrics import mean_squared_error
reshaped_y = padded_y.reshape(1,-1)
mse = mean_squared_error(reshaped_y, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.00048669084220117844


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
