In [1]:
import pickle
import os
import base64

file_path = r'D:\LinkedInPost.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
x=img_dict['x']
y=img_dict['y']

In [62]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_sequences = pad_sequences(sequences, maxlen=500, padding='post', dtype='float32')

#print("Padded sequences:\n", padded_sequences)
#padded_sequences

In [65]:
#padded_sequences.shape

In [66]:
padded_y=np.array(y)
#padded_y.shape

In [67]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Define the number of folds for cross-validation
k = 2

# Initialize lists to store performance metrics across folds
mse_scores = []

# Create a Ridge regression model
ridge_model = Ridge(alpha=1.0)  # You can adjust alpha as needed

# Create a KFold object
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform k-fold cross-validation
for train_index, test_index in kf.split(padded_sequences):
    x_train, x_test = padded_sequences[train_index], padded_sequences[test_index]
    y_train, y_test = padded_y[train_index], padded_y[test_index]
    
    # Fit the model on the training data
    ridge_model.fit(x_train, y_train)
    
    # Predict on the test data
    y_pred = ridge_model.predict(x_test)
    print("Predictions:\n", y_pred)
    # Calculate performance metrics
    mse = mean_squared_error(y_test, y_pred)
    
    
    # Append scores to lists
    mse_scores.append(mse)
    

# Calculate mean and standard deviation of scores across folds
mean_mse = np.mean(mse_scores)
std_mse = np.std(mse_scores)

print(f"Mean MSE across {k}-fold CV: {mean_mse:.6f} ± {std_mse:.6f}")

Predictions:
 [[0.18554631 0.20481706 0.21380205 0.18000655 0.21720672]
 [0.18554631 0.20481706 0.21380205 0.18000655 0.21720672]
 [0.18554987 0.20481467 0.21380123 0.18001302 0.21719956]
 [0.18553023 0.20481612 0.21380743 0.18000941 0.21721692]
 [0.18553635 0.20481761 0.2137997  0.18002504 0.21720105]
 [0.18553542 0.20481591 0.21380395 0.18001112 0.21721351]
 [0.18555069 0.20481907 0.2137962  0.18001245 0.21720009]
 [0.18554257 0.20485109 0.21377578 0.17996486 0.21724305]
 [0.18551162 0.2048238  0.21379848 0.18001123 0.2172272 ]
 [0.18554631 0.20481706 0.21380205 0.18000655 0.21720672]
 [0.18551053 0.20483787 0.21380655 0.1800153  0.2172144 ]
 [0.18547398 0.2048476  0.21379082 0.18000588 0.21725175]
 [0.18547751 0.2048414  0.21376693 0.17997688 0.21728411]
 [0.18555117 0.20482072 0.21380089 0.17999311 0.21721199]
 [0.18556394 0.2048115  0.2138137  0.18000813 0.21718532]
 [0.18554695 0.2048188  0.21379161 0.18001679 0.21720646]
 [0.18554455 0.20483197 0.21381289 0.17996648 0.21721841]


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [70]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [69]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
# Create a Ridge regression model with regularization strength (alpha) set to 1.0
ridge_model1 = Ridge(alpha=1.0)

# Train the model
ridge_model1.fit(x_train, y_train)

# Predictions
y_pred = ridge_model1.predict(x_test)

# Print the predictions
print("Predictions:\n", y_pred)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18490319 0.2056705  0.21358567 0.18078002 0.21638085]
 [0.18491857 0.20565535 0.21358305 0.18077321 0.21638812]
 [0.18491456 0.20566142 0.21358873 0.1807746  0.21637744]
 [0.18491298 0.20565388 0.21358055 0.18074895 0.2164157 ]
 [0.18491596 0.20565191 0.21360789 0.1806957  0.21644063]
 [0.1849141  0.20567694 0.21358314 0.18076843 0.21638034]]
Mean Squared Error: 0.0016653946532737857


In [71]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
# Create a Lasso regression model with regularization strength (alpha) set to 1.0
lasso_model = Lasso(alpha=0.5)

# Train the model
lasso_model.fit(x_train, y_train)

# Predictions
y_pred = lasso_model.predict(x_test)
# Print the predictions
print("Predictions:\n", y_pred)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Predictions:
 [[0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]
 [0.18490568 0.20566039 0.2135849  0.18075472 0.21641508]]
Mean Squared Error: 0.0016654065386174275


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [73]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Assuming x_train, y_train, x_test, and y_test are already defined and loaded

# Fit the multioutput regressor to the training data
model = LinearRegression()
model.fit(x_train, y_train)

# Predict using the fitted model
y_pred = model.predict(x_test)

# Apply sigmoid function to the predictions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)
y_test = np.array(y_test, dtype=float)
#print(y_test)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[0.5464284  0.5516897  0.55261695 0.5458087  0.55292594]
 [0.54487693 0.54838336 0.56851435 0.541001   0.54809755]
 [0.53601027 0.55088574 0.5917594  0.5252817  0.54565966]
 [0.562377   0.5462914  0.53495014 0.55429167 0.5533119 ]
 [0.55984807 0.55288225 0.5379358  0.51512253 0.5849682 ]
 [0.5533969  0.5410319  0.56646943 0.55094284 0.5323364 ]]
Mean Squared Error: 0.12498101270506956


In [74]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [75]:
import numpy as np
#from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_train = np.array(y_train, dtype=float)

# Transform the input features to polynomial features
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

# Fit the multioutput regressor to the transformed training data
model1 = LinearRegression()
model1.fit(x_train_poly, y_train)

# Predict using the fitted model on the transformed test data
y_pred = model1.predict(x_test_poly)
y_pred_sigmoid = sigmoid(y_pred)

# Print the predictions
print("Predictions after applying sigmoid:\n", y_pred_sigmoid)

# Evaluate the model
y_test = np.array(y_test, dtype=float)
mse = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse)

Predictions after applying sigmoid:
 [[5.4793280e-01 5.4703689e-01 5.5759311e-01 5.5002207e-01 5.4762661e-01]
 [1.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 0.0000000e+00]
 [9.9966073e-01 2.0489241e-09 1.0000000e+00 1.0000000e+00 2.4903213e-13]
 [1.0000000e+00 8.5187808e-37 1.0000000e+00 1.0000000e+00 0.0000000e+00]
 [6.3593062e-03 9.9999905e-01 6.1844395e-07 2.7965407e-06 1.0000000e+00]
 [9.9483407e-01 2.6499347e-06 9.9999917e-01 9.9999630e-01 7.9452160e-09]]
Mean Squared Error: 0.3377645429005424


D:\anacondafolder\envs\testenv\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in exp
  


In [76]:
from sklearn.ensemble import RandomForestRegressor
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, padded_y, test_size=0.1, random_state=42)

In [77]:
# Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
rf_mse = mean_squared_error(y_test, y_pred_rf)
print(f"Random Forest Regressor MSE: {rf_mse}")

Random Forest Regressor MSE: 0.0018165241791800704


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)


# new prediction

In [78]:
import pickle
import os
import base64

file_path = r'D:\new_post.pickle'
with open(file_path, 'rb') as f:
    encoded_data = f.read()

# Decode the Base64-encoded data
decoded_bytes = base64.b64decode(encoded_data)

# Deserialize the object using pickle
img_dict = pickle.loads(decoded_bytes)
#print(img_dict.keys())
x=img_dict['x']
y=img_dict['y']

In [79]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

sequences = x
padded_x = pad_sequences(sequences, maxlen=500, padding='post', dtype='float32')

In [80]:
padded_y=np.array(y[10])
padded_y

array(['0.18', '0.21', '0.23', '0.14', '0.25'], dtype='<U4')

In [81]:
reshaped_data = padded_x[10].reshape(1, -1)
y_pred = ridge_model.predict(reshaped_data)

# Print the predictions
print("Predictions:\n", y_pred)

Predictions:
 [[0.18234211 0.20636892 0.21268255 0.18197294 0.21697119]]


In [82]:
from sklearn.metrics import mean_squared_error
reshaped_y = padded_y.reshape(1,-1)
mse = mean_squared_error(reshaped_y, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.0006342388317382275


D:\anacondafolder\envs\testenv\lib\site-packages\sklearn\metrics\_regression.py:95: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  y_true = check_array(y_true, ensure_2d=False, dtype=dtype)
